---
name: Test Windows

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  merge_group:

env:
  TWITCH_PUBSUB_SERVER_TAG: v1.0.12
  HTTPBOX_TAG: v0.2.1
  QT_QPA_PLATFORM: minimal
  CONAN_VERSION: 2.11.0
  CHATTERINO_SKIP_GIT_GEN: 1

concurrency:
  group: test-windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-windows:
    name: "Test ${{ matrix.os }}, Qt ${{ matrix.qt-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        qt-version: [6.9.3]
      fail-fast: false
    env:
      QT_MODULES: qtimageformats
      C2_USE_OPENSSL3: ${{ case(startsWith(matrix.qt-version, '6.'), 'True', 'False') }}
      C2_CONAN_CACHE_SUFFIX: ${{ case(startsWith(matrix.qt-version, '6.'), '-QT6', '') }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.3.0
        with:
          cache: true
          cache-key-prefix: ${{ runner.os }}-QtCache-${{ matrix.qt-version }}-v2
          modules: ${{ env.QT_MODULES }}
          version: ${{ matrix.qt-version }}

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Setup sccache
        uses: hendrikmuhs/ccache-action@v1.2.22
        with:
          variant: sccache
          save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          key: sccache-test-${{ matrix.os }}-${{ matrix.qt-version }}
          restore-keys: |
            sccache-test-${{ matrix.os }}-${{ matrix.qt-version }}
            sccache-build-windows-x64

      - name: Cache conan packages
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ runner.arch }}-conan-user-${{ hashFiles('**/conanfile.py') }}-QT6
          path: ~/.conan2/
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-conan-user-

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip

      - name: Install Conan
        run: |
          pip install "conan==${{ env.CONAN_VERSION }}"

      - name: Setup Conan
        run: |
          conan --version
          conan profile detect -f

      - name: Install dependencies
        run: |
          mkdir build-test
          cd build-test
          conan install .. `
              -s build_type=Release `
              -c tools.cmake.cmaketoolchain:generator="Ninja" `
              -b missing `
              --output-folder=. `
              -o with_openssl3="$Env:C2_USE_OPENSSL3"

      - name: Install CRT
        run: |
          mkdir -Force build-test/bin
          cp "$((ls $Env:VCToolsRedistDir/onecore/x64 -Filter '*.CRT')[0].FullName)/*" build-test/bin

      - name: Cache httpbox
        id: cache-httpbox
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ runner.arch }}-httpbox-${{ env.HTTPBOX_TAG }}
          path: httpbox

      - name: Install httpbox
        if: steps.cache-httpbox.outputs.cache-hit != 'true'
        run: |
          mkdir httpbox
          Invoke-WebRequest -Uri "https://github.com/Chatterino/httpbox/releases/download/${{ env.HTTPBOX_TAG }}/httpbox-x86_64-pc-windows-msvc.zip" -outfile "httpbox.zip"
          Expand-Archive httpbox.zip -DestinationPath httpbox
          rm httpbox.zip

      - name: Build
        run: |
          cmake `
              -G Ninja `
              -DCMAKE_BUILD_TYPE=Release `
              -DBUILD_TESTS=On `
              -DBUILD_APP=OFF `
              -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" `
              -DUSE_PRECOMPILED_HEADERS=On `
              -DCHATTERINO_SPELLCHECK=Off `
              ..
          cmake --build . --parallel
        working-directory: build-test

      - name: Cache Twitch PubSub Server Test
        id: cache-pubsub-server
        uses: actions/cache@v5
        with:
          key: ${{ runner.os }}-${{ runner.arch }}-pubsub-server-${{ env.TWITCH_PUBSUB_SERVER_TAG }}
          path: pubsub-server-test

      - name: Download and extract Twitch PubSub Server Test
        if: steps.cache-pubsub-server.outputs.cache-hit != 'true'
        run: |
          mkdir pubsub-server-test
          Invoke-WebRequest -Uri "https://github.com/Chatterino/twitch-pubsub-server-test/releases/download/${{ env.TWITCH_PUBSUB_SERVER_TAG }}/server-${{ env.TWITCH_PUBSUB_SERVER_TAG }}-windows-amd64.zip" -outfile "pubsub-server.zip"
          Expand-Archive pubsub-server.zip -DestinationPath pubsub-server-test
          rm pubsub-server.zip

      - name: Set test retry policy
        run: |
          if ("${{ github.event_name }}" -eq "pull_request" -or "${{ github.event_name }}" -eq "merge_group")
          {
            "CTEST_REPEAT_COUNT=2" >> $Env:GITHUB_ENV
          }
          elseif ("${{ github.event_name }}" -eq "push" -and "${{ github.ref }}" -eq "refs/heads/main")
          {
            "CTEST_REPEAT_COUNT=3" >> $Env:GITHUB_ENV
          }
          else
          {
            "CTEST_REPEAT_COUNT=3" >> $Env:GITHUB_ENV
          }

      - name: Test
        timeout-minutes: 30
        run: |
          ..\httpbox\httpbox.exe --port 9051 &
          cd ..\pubsub-server-test
          ./server 127.0.0.1:9050 127.0.0.1:9052 &
          cd ..\build-test
          ctest --repeat until-pass:$Env:CTEST_REPEAT_COUNT --output-on-failure
        working-directory: build-test

      - name: Clean Conan cache
        run: conan cache clean --source --build --download "*"
